#!/usr/bin/env python3
'''
Test code for gcoder that draws a simple couple of squares.
---
    Leonerdo: Interactive art drawing robot
    Copyright (C) 2016  Matthew Bells

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import gcoder

def square(corner):
    points=[]
    points.append([[-corner,-corner]])
    points.append([[corner,-corner]])
    points.append([[corner,corner]])
    points.append([[-corner,corner]])
    points.append([[-corner,-corner]])
    return points

contours=[]

for s in range(100, 10, -10):
    contours.append(square(s))

print(contours)

g = gcoder.GCoder()
g.input_bounds(100, 100, -100, -100)
g.add_lines(contours)
g.write('images/square-100.ngc')
